"""create_tables

Revision ID: 91917ee41c5e
Revises: 
Create Date: 2023-12-16 21:04:20.357848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91917ee41c5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Car')
    op.drop_table('Order')
    op.drop_table('AutoMechanic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AutoMechanic',
                    sa.Column('Id', sa.INTEGER(), nullable=False),
                    sa.Column('Full_name', sa.VARCHAR(), nullable=False),
                    sa.Column('Experience', sa.INTEGER(), nullable=False),
                    sa.Column('Discharge', sa.VARCHAR(), nullable=False),
                    sa.Column('Planned_end_date', sa.DATETIME(), nullable=False),
                    sa.Column('Personnel_Number', sa.INTEGER(), nullable=False),
                    sa.PrimaryKeyConstraint('Id')
                    )
    op.create_table('Order',
                    sa.Column('Id', sa.INTEGER(), nullable=False),
                    sa.Column('Price', sa.INTEGER(), nullable=False),
                    sa.Column('Type_of_work', sa.VARCHAR(), nullable=False),
                    sa.Column('Date_of_issue', sa.DATETIME(), nullable=False),
                    sa.Column('Planned_end_date', sa.DATETIME(), nullable=False),
                    sa.Column('Real_end_date', sa.DATETIME(), nullable=False),
                    sa.Column('car_id', sa.INTEGER(), nullable=False),
                    sa.Column('auto_mechanic_id', sa.INTEGER(), nullable=False),
                    sa.ForeignKeyConstraint(['auto_mechanic_id'], ['AutoMechanic.Id'], ),
                    sa.ForeignKeyConstraint(['car_id'], ['Car.Id'], ),
                    sa.PrimaryKeyConstraint('Id')
                    )
    op.create_table('Car',
                    sa.Column('Id', sa.INTEGER(), nullable=False),
                    sa.Column('Owners_full_name', sa.VARCHAR(), nullable=False),
                    sa.Column('Brand', sa.VARCHAR(), nullable=False),
                    sa.Column('Number', sa.INTEGER(), nullable=False),
                    sa.Column('Year_of_issue', sa.INTEGER(), nullable=False),
                    sa.PrimaryKeyConstraint('Id')
                    )
    # ### end Alembic commands ###
