"""json-field

Revision ID: 992801a8628a
Revises: e426a4a15062
Create Date: 2023-12-19 15:43:30.140830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON, JSONB

# revision identifiers, used by Alembic.
revision: str = '992801a8628a'
down_revision: Union[str, None] = 'e426a4a15062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('your_table_name', sa.Column('json_field', JSONB, nullable=True))
    op.execute("UPDATE your_table_name SET json_field = '{}'")  # Populate the JSON field with initial data
    op.create_index('ix_json_field_gin', 'your_table_name', ['json_field'], postgresql_using='gin',
                    postgresql_ops={"json_field": "jsonb_path_ops"})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_json_field_gin', 'your_table_name')
    op.drop_column('your_table_name', 'json_field')
    # ### end Alembic commands ###
