"""create_indexes

Revision ID: e426a4a15062
Revises: 91917ee41c5e
Create Date: 2023-12-16 21:06:34.150999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e426a4a15062'
down_revision: Union[str, None] = '91917ee41c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_auto_mechanic_full_name', 'AutoMechanic', ['Full_name'])
    op.create_index('idx_auto_mechanic_personnel_number', 'AutoMechanic', ['Personnel_Number'])

    op.create_index('idx_car_owners_full_name', 'Car', ['Owners_full_name'])
    op.create_index('idx_car_brand', 'Car', ['Brand'])

    op.create_index('idx_order_price', 'Order', ['Price'])
    op.create_index('idx_order_type_of_work', 'Order', ['Type_of_work'])
    op.create_index('idx_order_date_of_issue', 'Order', ['Date_of_issue'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_auto_mechanic_full_name', table_name='AutoMechanic')
    op.drop_index('idx_auto_mechanic_personnel_number', table_name='AutoMechanic')

    op.drop_index('idx_car_owners_full_name', table_name='Car')
    op.drop_index('idx_car_brand', table_name='Car')

    op.drop_index('idx_order_price', table_name='Order')
    op.drop_index('idx_order_type_of_work', table_name='Order')
    op.drop_index('idx_order_date_of_issue', table_name='Order')
    # ### end Alembic commands ###
